baseURL = "https://anuram.at"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-V2"

languageCode = "en-us"

title = "CHANGE ME"
enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = "CHANGE ME"
enableEmoji = true


[params.author]
  name = "author name"
  about = "site author about"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "site description"
  themeColor = "#494f5c"

  homeSubtitle = "home subtitle"
  gitUrl = "https://github.com/anuramat/anuramat.github.io"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "CHANGE ME READ TIME"
  shareSocial = true
  
  [[params.socialLinks]]
    name = "mastodon"
    url = "https://joinmastodon.org/"

  [[params.socialLinks]]
    name = "x"
    url = "https://twitter.com/"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-hugo/"
    weight = 20
